# Generated by Django 2.2.4 on 2019-08-31 12:51

import bets_manager.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets_manager', '0002_singlebet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebet',
            name='result',
            field=bets_manager.fields.ResultField(choices=[('won', 'WON'), ('won_half', 'WON_HALF'), ('returned', 'RETURNED'), ('lost', 'LOST'), ('lost_half', 'LOST_HALF')], max_length=20),
        ),
    ]
