# Generated by Django 2.2.4 on 2019-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets_manager', '0003_auto_20190831_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlebet',
            name='detail',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
